package backend;

/**
 * Easy class to store the data encapsuled in a message.
 * Easy to add new data to a message or remove some!
 * To determine the partner of a conversation, look at the
 * parent Conversation class.
 */
public class ConversationMessage {
	
	// Data stored in a message
	private final boolean isSentMessage;
	private final String message;
	private final String timeStamp;
	
	/**
	 * ConversationMessage constructor. Used to hold all the
	 * data needed about an individual message.
	 * @param sentMsgToSet - a boolean indicating if the message was sent by us
	 * @param timeToSet - a Date instance of the formatted time of this message
	 * @param messageToSet - a String of the actual message's content
	 */
	public ConversationMessage(boolean sentMsgToSet, String timeToSet, String messageToSet) {
		isSentMessage = sentMsgToSet;
		timeStamp = timeToSet;
		message = messageToSet;
		checkRep();
	}
	
	/**
	 * Representation invariant for ConversationMessage:
	 * message and timeStamp are not null.
	 * Only needs to be run after creation as message is a final field.
	 */
	private void checkRep() {
		assert timeStamp != null;
		assert message != null;
	}
	
	/**
	 * Method to tell if this is a sent message,
	 * rather than an incoming message.
	 * @return a Boolean indicating if this was a sent message
	 */
	public boolean isSentMessage() {
		return isSentMessage;
	}
	
	/**
	 * Method to get the time when this message was sent or received.
	 * This message comes pre-formatted.
	 * @return a String of the time of this message
	 */
	public String getTimeStamp() {
		return timeStamp;
	}
	
	/**
	 * Method to get the content of this message.
	 * @return a String with this message's content.
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * The hashCode() method was generated by Eclipse.
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (isSentMessage ? 1231 : 1237);
		result = prime * result + ((message == null) ? 0 : message.hashCode());
		result = prime * result
				+ ((timeStamp == null) ? 0 : timeStamp.hashCode());
		return result;
	}

	/**
	 * The equals() method was generated by Eclipse.
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ConversationMessage other = (ConversationMessage) obj;
		if (isSentMessage != other.isSentMessage)
			return false;
		if (message == null) {
			if (other.message != null)
				return false;
		} else if (!message.equals(other.message))
			return false;
		if (timeStamp == null) {
			if (other.timeStamp != null)
				return false;
		} else if (!timeStamp.equals(other.timeStamp))
			return false;
		return true;
	}

	
}